spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=direccion-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://direccion-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/direcciones/**

spring.cloud.gateway.server.webflux.routes[1].id=local-service-locales
spring.cloud.gateway.server.webflux.routes[1].uri=lb://local-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/locales/**

spring.cloud.gateway.server.webflux.routes[2].id=local-service-catalogo
spring.cloud.gateway.server.webflux.routes[2].uri=lb://local-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/rubros-local/**,/categorias-item/**,/items/**,/locales-horario/**,/promociones/**

spring.cloud.gateway.server.webflux.routes[3].id=rider-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://rider-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/riders/**,/tipos-vehiculo/**,/estados-asignacion-rider/**,/asignaciones-rider/**

spring.cloud.gateway.server.webflux.routes[4].id=user-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/auth/**,/usuarios/**,/usuarios-direcciones/**

spring.cloud.gateway.server.webflux.routes[5].id=order-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/estados-pedido/**,/pedidos/**

spring.cloud.gateway.server.webflux.routes[6].id=payment-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://payment-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/pagos/**

spring.cloud.gateway.server.webflux.routes[7].id=cart-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://cart-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/carritos/**

spring.cloud.gateway.server.webflux.routes[8].id=notification-service
spring.cloud.gateway.server.webflux.routes[8].uri=lb://notification-service
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/notificaciones/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
